version: "3.9"
services:
  client:
    container_name: client
    build:
      context: zpr-front
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    stdin_open: true
    env_file: .env
  server:
    container_name: server
    build:
      context: zpr-backend
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: app.py
    ports:
      - "5555:5000"
    stdin_open: true
    entrypoint:
      - pipenv
      - run
      - app
